apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: sungho
type: Opaque
data:
  FLASK_SECRET_KEY: "MTJhYmNkZWYxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg="  # 생성된 실제 base64 값
  MARIADB_PASSWORD: "Tjk2UjZmdGV0Sg=="
  REDIS_PASSWORD: "dW5kSUp6RmlSaQ=="  # undIJzFiRi를 base64로 인코딩
  KAFKA_PASSWORD: ""