apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-local
  namespace: sungho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-local
  template:
    metadata:
      labels:
        app: frontend-local
    spec:
      containers:
      - name: frontend
        image: ghcr.io/hadonas/aks-demo-frontend:local
        ports:
        - containerPort: 80
        env:
        # OpenTelemetry 환경변수
        - name: VUE_APP_OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://collector-opentelemetry-collector.otel-collector-rnr.svc.cluster.local:4318/v1/traces"
        - name: VUE_APP_OTEL_SERVICE_NAME
          value: "aks-demo-frontend"
        - name: VUE_APP_OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: VUE_APP_OTEL_ENVIRONMENT
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sungho
spec:
  type: NodePort
  selector:
    app: frontend-local
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
