apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sungho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: acr-registry
      containers:
      - name: frontend
        image: ktech4.azurecr.io/aks-demo-frontend:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        # OpenTelemetry 환경변수
        - name: VUE_APP_OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://collector-opentelemetry-collector.otel-collector-rnr.svc.cluster.local:4318/v1/traces"
        - name: VUE_APP_OTEL_SERVICE_NAME
          value: "aks-demo-frontend"
        - name: VUE_APP_OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: VUE_APP_OTEL_ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sungho
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083