# Kafka Helm Bitnami Values
# https://github.com/bitnami/charts/tree/main/bitnami/kafka

## Kafka 설정
kafka:
  replicaCount: 1
  
  auth:
    clientProtocol: plaintext
    interBrokerProtocol: plaintext
    tls:
      enabled: false
  
  persistence:
    enabled: false  # 테스트용으로 PVC 비활성화
  
  # 리소스 제한 추가
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  
  zookeeper:
    enabled: true
    persistence:
      enabled: false  # 테스트용으로 PVC 비활성화
    
    # Zookeeper 리소스 제한
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"
      requests:
        memory: "128Mi"
        cpu: "125m"

## 서비스 설정
service:
  type: ClusterIP

## 네임스페이스
namespaceOverride: "sungho"
