apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-local
  template:
    metadata:
      labels:
        app: mariadb-local
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "testpassword"
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_USER
          value: "testuser"
        - name: MYSQL_PASSWORD
          value: "testpassword"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-data
        emptyDir: {}
      - name: init-script
        configMap:
          name: mariadb-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-local
spec:
  type: ClusterIP
  selector:
    app: mariadb-local
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-script
data:
  init.sql: |
    USE testdb;
    
    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        message TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        user_id VARCHAR(255)
    );
    
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
